import { describe, expect, it } from '@colorclash/test-fixtures';
import { PatchError, patchBuildGradle, patchVariables } from './android-release.js';

/**
 * The Android project is generated by `npx cap add android` inside CI, so it
 * does not exist in this repository and cannot be built here. What *can* be
 * tested — and is worth testing, because a silent miss produces an unsigned or
 * mis-versioned upload — is the patcher itself, against a fixture that mirrors
 * the file Capacitor actually emits.
 */

const CAPACITOR_BUILD_GRADLE = `apply plugin: 'com.android.application'

android {
    namespace "com.geeksforgames.colorclash"
    compileSdk rootProject.ext.compileSdkVersion
    defaultConfig {
        applicationId "com.geeksforgames.colorclash"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        aaptOptions {
             ignoreAssetsPattern '!.svn:!.git'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    flatDir{
        dirs '../capacitor-cordova-android-plugins/src/main/libs', 'libs'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':capacitor-android')
}

apply from: 'capacitor.build.gradle'
`;

const CAPACITOR_VARIABLES = `ext {
    minSdkVersion = 22
    compileSdkVersion = 34
    targetSdkVersion = 34
    androidxActivityVersion = '1.9.2'
    androidxAppCompatVersion = '1.7.0'
}
`;

describe('android-release — Gradle patcher', () => {
  it('injects a release signing config', () => {
    const out = patchBuildGradle(CAPACITOR_BUILD_GRADLE, {
      versionCode: 7,
      versionName: '1.2.0',
    });
    expect(out).toContain('signingConfigs {');
    expect(out).toContain('release {');
    expect(out).toContain('CLASH_KEYSTORE_PATH');
  });

  it('points the release build type at the signing config', () => {
    const out = patchBuildGradle(CAPACITOR_BUILD_GRADLE, {
      versionCode: 1,
      versionName: '1.0.0',
    });
    // The line must land inside buildTypes.release, not signingConfigs.release.
    const buildTypes = out.slice(out.indexOf('buildTypes {'));
    expect(buildTypes).toContain('signingConfig signingConfigs.release');
  });

  it('reads credentials from the environment, never from a checked-in file', () => {
    const out = patchBuildGradle(CAPACITOR_BUILD_GRADLE, {
      versionCode: 1,
      versionName: '1.0.0',
    });
    expect(out).toContain('System.getenv("CLASH_KEYSTORE_PASSWORD")');
    // A keystore.properties file in the repo is exactly what we are avoiding.
    expect(out.includes('keystore.properties')).toBe(false);
  });

  it('sets the version code and name', () => {
    const out = patchBuildGradle(CAPACITOR_BUILD_GRADLE, {
      versionCode: 42,
      versionName: '3.1.4',
    });
    expect(out).toContain('versionCode 42');
    expect(out).toContain('versionName "3.1.4"');
    expect(out.includes('versionCode 1\n')).toBe(false);
  });

  it('is idempotent — running twice does not double-inject', () => {
    const once = patchBuildGradle(CAPACITOR_BUILD_GRADLE, {
      versionCode: 2,
      versionName: '1.0.1',
    });
    const twice = patchBuildGradle(once, { versionCode: 2, versionName: '1.0.1' });
    expect(twice).toBe(once);
    expect(count(twice, 'signingConfigs {')).toBe(1);
    expect(count(twice, 'signingConfig signingConfigs.release')).toBe(1);
  });

  it('fails loudly when the file is not what we expect', () => {
    // The dangerous outcome is a silent no-op producing an unsigned upload.
    expect(() =>
      patchBuildGradle('plugins { id "com.android.application" }', {
        versionCode: 1,
        versionName: '1.0.0',
      }),
    ).toThrow('android');

    expect(() =>
      patchBuildGradle('android {\n  defaultConfig { versionCode 1 }\n}', {
        versionCode: 1,
        versionName: '1.0.0',
      }),
    ).toThrow('buildTypes');
  });

  it('pins the SDK levels so a Capacitor bump cannot drop them', () => {
    const out = patchVariables(CAPACITOR_VARIABLES, {
      compileSdk: 35,
      targetSdk: 35,
      minSdk: 23,
    });
    expect(out).toContain('compileSdkVersion = 35');
    expect(out).toContain('targetSdkVersion = 35');
    expect(out).toContain('minSdkVersion = 23');
    // Unrelated entries are left alone.
    expect(out).toContain("androidxActivityVersion = '1.9.2'");
  });

  it('fails if variables.gradle loses an expected key', () => {
    expect(() =>
      patchVariables('ext {\n  minSdkVersion = 22\n}', {
        compileSdk: 35,
        targetSdk: 35,
        minSdk: 23,
      }),
    ).toThrow('compileSdkVersion');
  });

  it('produces a build.gradle that still parses as balanced Groovy', () => {
    const out = patchBuildGradle(CAPACITOR_BUILD_GRADLE, {
      versionCode: 5,
      versionName: '2.0.0',
    });
    // A brace-count mismatch is the classic symptom of a bad text injection.
    expect(count(out, '{')).toBe(count(out, '}'));
  });
});

function count(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

export { PatchError };
